# Name: S Raghav Tejas

# Class: 7 'B' CSE

In [1]:
#ANN Backpropogation

import numpy as np
x= np.array(([2,9],[1,5],[3,6]),dtype= float)
y=np.array(([92],[86],[89]),dtype= float)
c= np.amax(x,axis=0)
print(c)
x=x/c
y=y/100
print(x)
print(y)

def sigmoid(x):
    return 1/(1+np.exp(-x))
def sigmoid_grad(x):
    return x*(1-x)

epoch=1000
eta=0.1
input_neurons=2
hidden_neurons=3
output_neurons=1

wh=np.random.uniform(size=(input_neurons,hidden_neurons))
print(wh)
bh=np.random.uniform(size=(1,hidden_neurons))
print(bh)
wout=np.random.uniform(size=(hidden_neurons,output_neurons))
print(wout)
bout=np.random.uniform(size=(1,output_neurons))
print(bout)

for i in range(epoch):
    h_ip=np.dot(x,wh)+bh
    print(h_ip)
    h_act= sigmoid(h_ip)
    o_ip=np.dot(h_act,wout)+bout
    output= sigmoid(o_ip)
    
    Eo=y-output
    outgrad= sigmoid_grad(output)
    d_output = Eo* outgrad
    print("the d_output is \n",d_output)
    
    Eh=d_output.dot(wout.T)
    hiddengrad= sigmoid_grad(h_act)
    d_hidden= Eh *hiddengrad
    wout += h_act.T.dot(d_output)*eta
    wh += x.T.dot(d_hidden)*eta
    
print("Normalized input: \n"+str(x))
print("Actual output: \n"+ str(y))
print("Predicted output: \n",output)


[3. 9.]
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]
[[0.44035065 0.12675355 0.87304127]
 [0.48509324 0.14457793 0.20043636]]
[[0.86921007 0.13957709 0.05342848]]
[[0.44948191]
 [0.19208763]
 [0.16663728]]
[[0.77837601]]
[[1.6478704  0.36865738 0.83589236]
 [1.28548986 0.26214934 0.45579577]
 [1.63295621 0.36271592 1.06009399]]
the d_output is 
 [[0.01924405]
 [0.01106721]
 [0.01422451]]
[[1.64822172 0.36891522 0.83608452]
 [1.28567786 0.26228728 0.45589864]
 [1.63329797 0.36296731 1.06028043]]
the d_output is 
 [[0.01899223]
 [0.0108587 ]
 [0.01399004]]
[[1.64857041 0.36917257 0.83627726]
 [1.28586447 0.26242497 0.45600182]
 [1.63363717 0.3632182  1.06046741]]
the d_output is 
 [[0.01874637]
 [0.0106552 ]
 [0.01376133]]
[[1.64891649 0.36942939 0.83647046]
 [1.28604967 0.26256237 0.45610525]
 [1.6339738  0.36346856 1.06065484]]
the d_output is 
 [[0.01850628]
 [0.01045655]
 [0.01353818]]
[[1.64925995 0.3696856  0.83666406]
 [1.286

 [0.00405271]]
[[1.67282946 0.38953468 0.85298331]
 [1.29885036 0.27332275 0.46494783]
 [1.65718024 0.38301058 1.07663175]]
the d_output is 
 [[0.00796268]
 [0.00184915]
 [0.00401278]]
[[1.67299403 0.3896854  0.85311268]
 [1.29893848 0.27340344 0.46501713]
 [1.65733947 0.38315655 1.07675654]]
the d_output is 
 [[0.00791722]
 [0.00181285]
 [0.00397336]]
[[1.6731575  0.38983526 0.85324135]
 [1.29902603 0.27348369 0.46508606]
 [1.65749763 0.38330167 1.07688065]]
the d_output is 
 [[0.00787231]
 [0.001777  ]
 [0.00393443]]
[[1.6733199  0.38998427 0.85336935]
 [1.29911299 0.27356347 0.46515462]
 [1.65765474 0.38344596 1.0770041 ]]
the d_output is 
 [[0.00782793]
 [0.00174158]
 [0.00389599]]
[[1.67348122 0.39013244 0.85349666]
 [1.29919938 0.27364281 0.46522283]
 [1.65781081 0.38358943 1.07712688]]
the d_output is 
 [[0.00778409]
 [0.00170661]
 [0.00385803]]
[[1.67364149 0.39027977 0.85362329]
 [1.2992852  0.2737217  0.46529067]
 [1.65796584 0.38373207 1.077249  ]]
the d_output is 
 [[0.0077

[[1.6837153  0.39981937 0.86189369]
 [1.30468124 0.27883145 0.46972245]
 [1.66768955 0.39294232 1.08520577]]
the d_output is 
 [[ 0.00543037]
 [-0.00015116]
 [ 0.00185284]]
[[1.6838138  0.3999155  0.86197755]
 [1.30473402 0.27888295 0.46976741]
 [1.66778437 0.3930348  1.08528622]]
the d_output is 
 [[ 0.00541136]
 [-0.00016597]
 [ 0.00183694]]
[[1.68391176 0.40001116 0.86206102]
 [1.30478651 0.27893421 0.46981215]
 [1.66787866 0.39312683 1.08536628]]
the d_output is 
 [[ 0.00539251]
 [-0.00018065]
 [ 0.00182119]]
[[1.68400918 0.40010635 0.86214408]
 [1.30483871 0.27898522 0.46985668]
 [1.66797243 0.39321841 1.08544595]]
the d_output is 
 [[ 0.00537383]
 [-0.0001952 ]
 [ 0.00180558]]
[[1.68410607 0.40020108 0.86222675]
 [1.30489063 0.27903599 0.46990099]
 [1.66806568 0.39330953 1.08552524]]
the d_output is 
 [[ 0.00535531]
 [-0.00020962]
 [ 0.00179011]]
[[1.68420243 0.40029535 0.86230902]
 [1.30494226 0.27908651 0.4699451 ]
 [1.66815841 0.39340021 1.08560415]]
the d_output is 
 [[ 0.005

 [1.67337203 0.39859345 1.09013241]]
the d_output is 
 [[ 0.00439383]
 [-0.00095272]
 [ 0.00099493]]
[[1.68970044 0.40577944 0.86710264]
 [1.30788915 0.28202633 0.47251553]
 [1.67343713 0.39865961 1.09019018]]
the d_output is 
 [[ 0.00438312]
 [-0.00096093]
 [ 0.00098617]]
[[1.6897681  0.40584837 0.86716294]
 [1.30792543 0.2820633  0.47254787]
 [1.67350192 0.39872549 1.09024769]]
the d_output is 
 [[ 0.00437249]
 [-0.00096908]
 [ 0.00097747]]
[[1.68983544 0.405917   0.86722297]
 [1.30796154 0.2821001  0.47258008]
 [1.67356638 0.39879108 1.09030496]]
the d_output is 
 [[ 0.00436194]
 [-0.00097716]
 [ 0.00096884]]
[[1.68990246 0.40598534 0.86728275]
 [1.30799747 0.28213676 0.47261214]
 [1.67363054 0.39885638 1.09036198]]
the d_output is 
 [[ 0.00435146]
 [-0.00098519]
 [ 0.00096027]]
[[1.68996915 0.4060534  0.86734228]
 [1.30803323 0.28217325 0.47264408]
 [1.67369438 0.39892141 1.09041875]]
the d_output is 
 [[ 0.00434105]
 [-0.00099316]
 [ 0.00095176]]
[[1.69003553 0.40612116 0.86740156

[[1.69465442 0.41094562 0.87161716]
 [1.31054648 0.28479829 0.47493818]
 [1.67816314 0.40357584 1.09448109]]
the d_output is 
 [[ 0.00367324]
 [-0.00150111]
 [ 0.00041053]]
[[1.69469985 0.41099431 0.87165962]
 [1.31057086 0.28482443 0.47496098]
 [1.67820627 0.40362193 1.09452127]]
the d_output is 
 [[ 0.00366737]
 [-0.00150554]
 [ 0.00040582]]
[[1.69474508 0.41104282 0.87170192]
 [1.31059513 0.28485048 0.47498369]
 [1.67824922 0.40366785 1.09456129]]
the d_output is 
 [[ 0.00366155]
 [-0.00150994]
 [ 0.00040115]]
[[1.69479013 0.41109116 0.87174408]
 [1.31061931 0.28487643 0.47500632]
 [1.678292   0.4037136  1.09460117]]
the d_output is 
 [[ 0.00365576]
 [-0.00151431]
 [ 0.0003965 ]]
[[1.69483499 0.41113933 0.87178608]
 [1.31064339 0.2849023  0.47502888]
 [1.67833458 0.40375919 1.0946409 ]]
the d_output is 
 [[ 0.00365   ]
 [-0.00151865]
 [ 0.00039188]]
[[1.69487967 0.41118733 0.87182792]
 [1.31066737 0.28492807 0.47505135]
 [1.67837699 0.4038046  1.09468048]]
the d_output is 
 [[ 0.003

the d_output is 
 [[ 0.00333342]
 [-0.00175643]
 [ 0.00013904]]
[[1.69750112 0.414059   0.87432566]
 [1.31207493 0.28647064 0.47639302]
 [1.68085652 0.40651096 1.097035  ]]
the d_output is 
 [[ 0.00332957]
 [-0.0017593 ]
 [ 0.00013598]]
[[1.69753536 0.41409732 0.8743589 ]
 [1.31209333 0.28649124 0.47641088]
 [1.68088877 0.40654692 1.09706621]]
the d_output is 
 [[ 0.00332574]
 [-0.00176217]
 [ 0.00013293]]
[[1.69756947 0.41413552 0.87439203]
 [1.31211166 0.28651177 0.47642868]
 [1.6809209  0.40658276 1.09709732]]
the d_output is 
 [[ 0.00332193]
 [-0.00176501]
 [ 0.00012991]]
[[1.69760346 0.41417361 0.87442505]
 [1.31212991 0.28653224 0.47644643]
 [1.68095291 0.40661848 1.09712833]]
the d_output is 
 [[ 0.00331815]
 [-0.00176784]
 [ 0.0001269 ]]
[[1.69763733 0.41421158 0.87445797]
 [1.31214811 0.28655265 0.47646413]
 [1.6809848  0.4066541  1.09715923]]
the d_output is 
 [[ 0.00331438]
 [-0.00177066]
 [ 0.00012391]]
[[1.69767107 0.41424943 0.87449079]
 [1.31216623 0.28657299 0.47648176]

[[1.69959983 0.41645629 0.8763984 ]
 [1.31320291 0.2877597  0.47750738]
 [1.6828254  0.4087508  1.09897434]]
the d_output is 
 [[ 3.10937671e-03]
 [-1.92328073e-03]
 [-3.83161220e-05]]
[[1.69962676 0.41648776 0.87642552]
 [1.31321739 0.28777663 0.47752196]
 [1.68285054 0.40878006 1.0989996 ]]
the d_output is 
 [[ 3.10675272e-03]
 [-1.92522673e-03]
 [-4.03848829e-05]]
[[1.6996536  0.41651915 0.87645255]
 [1.31323182 0.28779351 0.4775365 ]
 [1.68287559 0.40880924 1.09902479]]
the d_output is 
 [[ 3.10414263e-03]
 [-1.92716221e-03]
 [-4.24424838e-05]]
[[1.69968035 0.41655045 0.87647952]
 [1.3132462  0.28781036 0.47755101]
 [1.68290056 0.40883835 1.09904991]]
the d_output is 
 [[ 3.10154636e-03]
 [-1.92908725e-03]
 [-4.44889941e-05]]
[[1.69970701 0.41658168 0.87650641]
 [1.31326054 0.28782716 0.47756547]
 [1.68292545 0.40886737 1.09907496]]
the d_output is 
 [[ 3.09896382e-03]
 [-1.93100190e-03]
 [-4.65244830e-05]]
[[1.69973359 0.41661282 0.87653323]
 [1.31327484 0.28784391 0.4775799 ]
 [1

[[1.70192104 0.41925317 0.87879561]
 [1.31445211 0.28926553 0.47879763]
 [1.68497819 0.41133516 1.10119548]]
the d_output is 
 [[ 0.00290418]
 [-0.00207475]
 [-0.00019945]]
[[1.70194105 0.41927811 0.87881686]
 [1.31446289 0.28927897 0.47880907]
 [1.6849966  0.41135805 1.10121504]]
the d_output is 
 [[ 0.00290261]
 [-0.0020759 ]
 [-0.00020068]]
[[1.70196099 0.41930299 0.87883806]
 [1.31447363 0.28929238 0.47882049]
 [1.68501495 0.41138088 1.10123456]]
the d_output is 
 [[ 0.00290105]
 [-0.00207705]
 [-0.0002019 ]]
[[1.70198089 0.41932783 0.87885922]
 [1.31448435 0.28930576 0.47883189]
 [1.68503326 0.41140366 1.10125404]]
the d_output is 
 [[ 0.00289949]
 [-0.00207819]
 [-0.00020312]]
[[1.70200073 0.41935261 0.87888033]
 [1.31449504 0.28931911 0.47884326]
 [1.68505151 0.41142639 1.10127347]]
the d_output is 
 [[ 0.00289794]
 [-0.00207933]
 [-0.00020433]]
[[1.70202052 0.41937734 0.8789014 ]
 [1.3145057  0.28933244 0.47885461]
 [1.68506971 0.41144908 1.10129286]]
the d_output is 
 [[ 0.002

[[1.70366245 0.4214891  0.88069129]
 [1.31539088 0.29047113 0.47981929]
 [1.68656931 0.41337466 1.10293158]]
the d_output is 
 [[ 0.00278168]
 [-0.00216427]
 [-0.00029496]]
[[1.70367827 0.42151007 0.88070897]
 [1.31539942 0.29048244 0.47982883]
 [1.68658365 0.41339366 1.10294768]]
the d_output is 
 [[ 0.00278071]
 [-0.00216497]
 [-0.00029572]]
[[1.70369406 0.421531   0.88072662]
 [1.31540794 0.29049373 0.47983834]
 [1.68659796 0.41341263 1.10296374]]
the d_output is 
 [[ 0.00277974]
 [-0.00216568]
 [-0.00029647]]
[[1.70370981 0.42155189 0.88074424]
 [1.31541644 0.29050501 0.47984785]
 [1.68661223 0.41343157 1.10297978]]
the d_output is 
 [[ 0.00277877]
 [-0.00216638]
 [-0.00029722]]
[[1.70372553 0.42157276 0.88076183]
 [1.31542492 0.29051627 0.47985733]
 [1.68662648 0.41345048 1.1029958 ]]
the d_output is 
 [[ 0.00277781]
 [-0.00216708]
 [-0.00029797]]
[[1.70374122 0.4215936  0.88077939]
 [1.31543338 0.29052751 0.4798668 ]
 [1.68664069 0.41346936 1.10301178]]
the d_output is 
 [[ 0.002

 [1.68779361 0.41504233 1.10433864]]
the d_output is 
 [[ 0.00270752]
 [-0.00221787]
 [-0.00035246]]
[[1.70503551 0.4233567  0.88225926]
 [1.31613231 0.2914794  0.48066534]
 [1.68780547 0.41505896 1.10435261]]
the d_output is 
 [[ 0.00270689]
 [-0.00221832]
 [-0.00035294]]
[[1.70504876 0.42337521 0.88227473]
 [1.31613947 0.2914894  0.48067369]
 [1.68781731 0.41507556 1.10436656]]
the d_output is 
 [[ 0.00270627]
 [-0.00221877]
 [-0.00035342]]
[[1.70506199 0.4233937  0.88229019]
 [1.31614662 0.29149938 0.48068203]
 [1.68782913 0.41509215 1.1043805 ]]
the d_output is 
 [[ 0.00270565]
 [-0.00221921]
 [-0.0003539 ]]
[[1.70507519 0.42341216 0.88230562]
 [1.31615375 0.29150936 0.48069037]
 [1.68784093 0.41510872 1.10439442]]
the d_output is 
 [[ 0.00270503]
 [-0.00221966]
 [-0.00035438]]
[[1.70508838 0.42343061 0.88232103]
 [1.31616088 0.29151932 0.48069869]
 [1.68785271 0.41512526 1.10440832]]
the d_output is 
 [[ 0.00270442]
 [-0.0022201 ]
 [-0.00035486]]
[[1.70510154 0.42344904 0.88233643

 [-0.00039427]]
[[1.70638276 0.42528729 0.88386646]
 [1.31686095 0.29252282 0.48153346]
 [1.68900104 0.41678292 1.10579566]]
the d_output is 
 [[ 0.0026529 ]
 [-0.00225675]
 [-0.00039456]]
[[1.70639414 0.42530401 0.88388033]
 [1.31686711 0.29253186 0.48154095]
 [1.68901107 0.41679778 1.10580806]]
the d_output is 
 [[ 0.00265253]
 [-0.00225702]
 [-0.00039485]]
[[1.70640552 0.42532073 0.88389419]
 [1.31687327 0.2925409  0.48154844]
 [1.68902109 0.41681264 1.10582045]]
the d_output is 
 [[ 0.00265215]
 [-0.00225728]
 [-0.00039514]]
[[1.70641687 0.42533742 0.88390804]
 [1.31687942 0.29254993 0.48155593]
 [1.6890311  0.41682748 1.10583282]]
the d_output is 
 [[ 0.00265178]
 [-0.00225754]
 [-0.00039543]]
[[1.70642822 0.42535411 0.88392187]
 [1.31688556 0.29255895 0.4815634 ]
 [1.68904109 0.41684231 1.10584519]]
the d_output is 
 [[ 0.0026514 ]
 [-0.00225781]
 [-0.00039572]]
[[1.70643955 0.42537078 0.8839357 ]
 [1.31689169 0.29256797 0.48157087]
 [1.68905107 0.41685712 1.10585754]]
the d_outp